--- 
production: 
  theme: simon
  site_name: Simon
  site_url: http://localhost:3000/
  support_email: support@baseapp2.local
  root_email: admin@baseapp2.local
  mailer: miguelregedor@gmail.com
  mailer_domain: gmail.com
  mailer_username: miguelregedor
  mailer_password: 123456
development: 
  theme: simon
  site_name: Simon
  site_url: http://localhost:3000/
  support_email: support@baseapp2.local
  root_email: admin@baseapp2.local
  mailer: miguelregedor@gmail.com
  mailer_domain: gmail.com
  mailer_username: miguelregedor
  mailer_password: 123456
test: 
  theme: simon
  site_name: Simon
  site_url: http://localhost:3000/
  support_email: support@baseapp2.local
  root_email: admin@baseapp2.local
  mailer: miguelregedor@gmail.com
  mailer_domain: gmail.com
  mailer_username: miguelregedor
  mailer_password: 123456
